repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: check-added-large-files
    -   id: check-case-conflict
    -   id: check-merge-conflict
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
    -   id: black
-   repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.404
    hooks:
    -   id: pyright
        additional_dependencies:
        -   pytest
